### ISSUE TITLE
How make backspace to work as expected?

### ISSUE THREAD

**Issue by NitzanShifrin** [zurb/tribute#410] opened 2020-02-10 14:37 UTC
Using delete/backspace should pop-menu if values are a match.

When making a typo, and deleting it, the menu disappears and not coming back of, even if there are matches.
Any change to add recalculation for this kind of situation?

Let's assume my contacts are:
John Smith, Anny Li

in my contentEditable div, I type
"@Ann", so far all good, the menu displaying "Anny Li".
Now ill make a typo, new text:
"@Annt" - the menu will disappear - still correct, no matches, no menu
If I delete the typo, I want my menu to pop back on.

Any way to do it?

**Comment by mkrauskopf** [comment] 2020-03-06 09:44
This seems to be a duplicate of #385.

**Comment by mxgl** [comment] 2020-03-09 18:53
This is fixed in 5.1.2!

**Closed** 2020-03-10 19:49 UTC

**Comment by manikantayarramsetti1** [comment] 2022-10-27 12:14
Removing characters one by one with backspace then auto suggesting is not working.How to apprach this thing any sample example or code. This is i m expecting (https://zurb.com/playground/tribute)
