### ISSUE TITLE
Textarea with absoluted position  is not working correctly

### ISSUE THREAD

**Issue by trungnv08** [zurb/tribute#318] opened 2019-09-09 09:02 UTC
In the example page, @mention is displayed at the top of  container element. It should be at the top of textarea.
If i set css: `position:absoluted;`, it work fine. 
Then i set position for that textera, it fails. 
![Screenshot (34)](https://user-images.githubusercontent.com/50939110/64517801-3a778580-d31b-11e9-8aa2-ddaa8b2f131a.png)

**Comment by sanjogs** [comment] 2019-09-10 19:37
#298

**Comment by mrsweaters** [comment] 2019-09-11 19:05
So this appears to be working fine if you specify in your tribute config a menuContainer that is positioned in the document, such as `document.body`.

**Comment by mrsweaters** [comment] 2019-09-11 19:07
Duplicate of https://github.com/zurb/tribute/issues/298

**Closed by mrsweaters** 2019-09-11 19:07 UTC
