### ISSUE TITLE
min file, Uncaught ReferenceError: Tribute is not defined

### ISSUE THREAD

**Issue by mariuszkrzaczkowski** [zurb/tribute#432] opened 2020-03-20 15:18 UTC
when I use min files I get an error:
Uncaught ReferenceError: Tribute is not defined

if I use without min or dist/tribute.js everything works

please check if the min files are correctly generated

version: 5.1.2 
file: dist/tribute.min.js
code: 
```
new Tribute();
```

**Comment by mrsweaters** [comment] 2020-03-25 17:09
I'm able to reproduce this with the version in the repo, but rebuilding it locally seems to resolve the issue. I'm not sure what happened. I'll try pushing up a new version to master and let's see if that resolves your problem.

**Comment by mrsweaters** [comment] 2020-03-25 17:13
ah, I see what the problem is, it is not exporting `Tribute` for min, it is exporting `tribute`. Will fix. Thank you.

**Comment by mrsweaters** [comment] 2020-03-25 17:18
Fixed in `5.1.3`! Thank you.

**Closed by mrsweaters** 2020-03-25 17:18 UTC
