### ISSUE TITLE
Behaves unexpectedly with contentEditable on Enter click after mentioning

### ISSUE THREAD

**Issue by TetianaP** [zurb/tribute#50] opened 2017-01-20 00:43 UTC
**How can we reproduce this bug?**

1. Create a simple application with `<div class="mentionable">Some text.</div>`
2. Initialize Tribute as `new Tribute({
	values: [
		{key: 'Phil Heartman', value: 'pheartman'},
		{key: 'Gordon Ramsey', value: 'gramsey'}
	]`
and attach to the contentEditable `tribute.attach(document.querySelectorAll('.mentionable'));`
3. Type `@` to see the possible options to mention
![image](https://cloud.githubusercontent.com/assets/21356403/22131034/34350942-df15-11e6-822e-2d69b3addea6.png)
 and select any
![image](https://cloud.githubusercontent.com/assets/21356403/22131048/57f8759e-df15-11e6-880b-caefa22e8a61.png)

4. Continue typing on the same line
![image](https://cloud.githubusercontent.com/assets/21356403/22131104/abcc9984-df15-11e6-9c6e-4eef34d34c3f.png)
 then press 'Enter' key
![image](https://cloud.githubusercontent.com/assets/21356403/22131123/d6655ed8-df15-11e6-9419-c5367f67c728.png)

**What did you expect to happen?**
Cursor moves to the next line.

**What happened instead?**
Cursor moves back to the place after mention and some part of a mention appears after it.
Trying to press 'Enter' again together with printing some text continue to insert some part of mentioning and moving cursor.

**Link (jsfiddle/plunkr) or Screenshot:**
![image](https://cloud.githubusercontent.com/assets/21356403/22131145/eea96552-df15-11e6-9072-6391b04400c2.png)

**Comment by mrsweaters** [comment] 2017-01-20 01:31
This was caused by not wrapping the content for contentEditable elements in markup in the `defaultSelectTemplate`. Fixed in https://github.com/zurb/tribute/commit/37fa6e8daebb2ddcd2a87a902b61bd3ee14a8eb8

Thank you!

**Closed by mrsweaters** 2017-01-20 01:31 UTC
Labels: bug

**Comment by TetianaP** [comment] 2017-01-20 03:13
Thank you!
