### ISSUE TITLE
When mention container is bottom of screen positioning (bottom) is incorrect

### ISSUE THREAD

**Issue by vick-subbu** [zurb/tribute#298] opened 2019-08-02 20:24 UTC
**How can we reproduce this bug?**

1. Step one
Go to the demo page: [https://zurb.github.io/tribute/example/](https://zurb.github.io/tribute/example/) 
2. Step two
Scroll down to a place until the traditional form elements are visible at the bottom of the page
3. Step three
Now start typing '@' you would notice that the **menuContainer** would be positioned incorrectly (bottom value is incorrectly calculated when top = 'auto') 

**What did you expect to happen?**
I expect the menuContainer to be positioned closer to the input or contenteditable div
**What happened instead?**
It was positioned incorrectly as shown in the attached GIF

![chrome-capture](https://user-images.githubusercontent.com/38239839/62396757-d813b400-b528-11e9-9077-66f87f8f5d72.gif)

**Link (jsfiddle/plunkr/codepen) or Screenshot:**
You can fork this Codepen as a base for reproducing your issue: 
https://codepen.io/mrsweaters/pen/OxxdWv?editors=1010#0

**Comment by vick-subbu** [comment] 2019-08-02 20:27
Is there an easy way to change/override the position values when top='auto'; Any help would be really appreciated, this one use-case is having us blocked to go live

**Comment by mrsweaters** [comment] 2019-08-07 18:58
I'm able to reproduce this, I'll have some time to look at this today. It looks like the float: right is causing an issue here.

**Comment by hessellund** [comment] 2019-08-23 07:49
Is there any news on this one? This is also a blocker for us.

**Comment by dessalines** [comment] 2019-08-31 15:55
I'm getting this too.

**Comment by dessalines** [comment] 2019-08-31 15:56
#178

**Comment by dessalines** [comment] 2019-09-06 19:47
Does anyone have a temp fix for this?

**Comment by sanjogs** [comment] 2019-09-10 19:40
Having the same issue, and it's blocking our go live. Any temporary fix?

**Comment by mrsweaters** [comment] 2019-09-11 19:06
https://github.com/zurb/tribute/issues/318#issuecomment-530521471

**Comment by mrsweaters** [comment] 2019-09-11 19:07
I'm closing this, this isn't an issue with tribute, but the way tribute is configured. Feel free to reopen if you have further issues or require further help!

**Closed by mrsweaters** 2019-09-11 19:07 UTC

**Comment by dessalines** [comment] 2019-09-11 21:43
I can verify this still is failing, even when using `menuContainer`. If the number of menu items exceeds the bottom of the screen, it repositions the entire dropdown to the top of the page, and you have to scroll up to see it.

**Comment by mrsweaters** [comment] 2019-09-11 21:48
@dessalines please share your issue in a codepen or submit a failing test.

**Comment by dessalines** [comment] 2019-09-11 22:08
Done: https://codepen.io/happydooby/pen/XWrqBKe

**Comment by mrsweaters** [comment] 2019-09-11 22:16
Ah, try making the parent of `menuContainer` relative so that absolute elements can be positioned within it. Example: https://codepen.io/mrsweaters/pen/MWgGBvo

Still, would be nice to flip the list.

**Comment by aldhsu** [comment] 2019-09-27 01:26
@mrsweaters I'm not sure if I'm doing something wrong but I can't get a `menuContainer` to position the menu correctly if it is not the last element. Repro: https://codepen.io/aldhsu/pen/WNeWMxm.

My hunch is this code should not add the `rect.top` or `rect.left` if the `menuContainer` is specified:

https://github.com/zurb/tribute/blob/a1110134b61233baf91ae38ece97f3a99b80295a/src/TributeRange.js#L480-L483

**Comment by loicndjoyi** [comment] 2020-05-14 14:43
@mrsweaters I'm having the same issue. Even if the menuContainer `position: relative`. I was able to make it work using this `body {position: relative}` but i'm not sure it is the best solution. Can you tell me If there is a better one? Thank you!

**Comment by mhrnik** [comment] 2021-08-17 16:57
> @mrsweaters I'm having the same issue. Even if the menuContainer `position: relative`. I was able to make it work using this `body {position: relative}` but i'm not sure it is the best solution. Can you tell me If there is a better one? Thank you!

yes @loicndjoyi this is the best solution
