### ISSUE TITLE
Typings file doesn't compile

### ISSUE THREAD

**Issue by PieterVerledens** [zurb/tribute#143] opened 2018-09-03 13:20 UTC
**How can we reproduce this bug?**
Try to reference the typings file and compile your code. The generic constructor throws an error.
An older version of the file works fine, but doesn't support all the features.

The changes I did on https://github.com/PieterVerledens/tribute allow me to use tribute and compile my project. 

Is anyone using the typings file as is without any issues?

**Comment by Gunirus** [comment] 2018-09-10 14:46
@benmerckx do you have any examples on how you're using this exactly?

**Comment by benmerckx** [comment] 2018-09-10 15:07
It works fine for me on typescript 2.9.1. Maybe I have something misconfigured but it doesn't seem that way (changing the constructor type gives me correct error messages). In any case if you can reproduce this, I think a simple PR changing the constructor to `constructor(options: TributeOptions<any>)` should do in this case? I see no way around this as it accepts an array of options too which can all be of different type.

**Comment by Gunirus** [comment] 2018-09-11 04:14
```
node_modules/tributejs/tributejs.d.ts:61:15 - error TS1092: Type parameters cannot appear on a constructor declaration.

61   constructor<T extends {}>(options: TributeOptions<T>)
                 ~~~~~~~~~~~~

```

Changing the constructor to constructor(options: TributeOptions<any>) seems to compile, I'll test if everything works.

**Comment by benmerckx** [comment] 2018-09-11 08:59
> Edit: creating an instance fails when I only change the constructor, I get
TypeError: tributejs_1.default is not a constructor

Have a look at `--esModuleInterop` or import as `import * as Tribute from 'tributejs'`

**Comment by Gunirus** [comment] 2018-09-13 07:31
> 
> 
> > Edit: creating an instance fails when I only change the constructor, I get
> > TypeError: tributejs_1.default is not a constructor
> 
> Have a look at `--esModuleInterop` or import as `import * as Tribute from 'tributejs'`
> 
> Edit: wait it's a type error - I have no clue what's going on then

Are you using the package 'as-is' in one of your projects?

**Comment by agarbund** [comment] 2018-09-17 21:04
I added another PR with a really easy change fixing that issue #149 
Note that current `.d.ts` file doesn't work with the latest Angular (v6).

**Comment by mrsweaters** [comment] 2018-09-19 00:05
Thank you guys for reporting this. Can you try the latest release, `3.3.5` and see if that solves your problem. I've merged in @agarbund's PR.

**Comment by agarbund** [comment] 2018-09-19 20:29
Yep, works for me.

**Comment by mrsweaters** [comment] 2018-09-19 21:35
Sweet! I'm closing it down. Let me know if you guys have any other TypeScript issues.

**Closed by mrsweaters** 2018-09-19 21:35 UTC
